// AUTO-GENERATED by astro-cms — do not edit manually

export interface Magazine {
  id: number
  title: string
  subtitle: string | null
  cover: { key: string; url: string } | null
  description: string | null
  issue_number: number | null
  category: 'Culture' | 'Musique' | 'Littérature' | 'Histoire' | 'Politique' | 'Société' | null
  published_at: string | null
  featured: boolean | null
  price: number | null
  pdf_file: { key: string; url: string } | null
  pages: number | null
  createdAt: string
  updatedAt: string
}

export interface Audio {
  id: number
  title: string
  artist: string
  cover: { key: string; url: string } | null
  audio_file: { key: string; url: string } | null
  description: string | null
  genre: 'Afrobeats' | 'Gospel' | 'Jazz' | 'Traditionnel' | 'Spoken Word' | 'Podcast' | 'Autre' | null
  duration: number | null
  published_at: string | null
  featured: boolean | null
  price: number | null
  free: boolean | null
  album: string | null
  lyrics: { key: string; url: string } | null
  createdAt: string
  updatedAt: string
}

export interface Video {
  id: number
  title: string
  thumbnail: { key: string; url: string } | null
  video_url: string | null
  video_file: { key: string; url: string } | null
  description: string | null
  category: 'Documentaire' | 'Interview' | 'Concert' | 'Clip' | 'Court-métrage' | 'Conférence' | 'Autre' | null
  duration: number | null
  published_at: string | null
  featured: boolean | null
  free: boolean | null
  createdAt: string
  updatedAt: string
}

export interface Hero_section {
  id: number
  page: 'home' | 'ebook' | 'audio' | 'video' | 'qui-sommes-nous'
  title: string
  subtitle: string | null
  background_image: { key: string; url: string } | null
  cta_label: string | null
  cta_url: string | null
  active: boolean | null
  order: number | null
  createdAt: string
  updatedAt: string
}
